### PR TITLE
Handle version information only in one place (DRY) + fix mac icon

### LINKED ISSUE #200: Mac release reports wrong version in Finder
The 0.5.7 mac version shows up under a different version in Finder: 0.5.2.

### PR DESCRIPTION
**Pull request by marco-m**
- put version information in CMakeLists.txt
- add templatized config.h and Info.plist
- actually copy Info.plist into bundle
- actually copy icon file into bundle (this makes the icon to show correctly In Finder)

Note: since this commit replaces Info.plist with a template handled by cmake, this effectively makes cmake the only reasonable way to build QSyncthingTray, and we must remove QSyncthingTray.pro. Personally I see only advantages in using cmake, but you might have a different opinion.

This also fixes #200.

### CODE REVIEW

**Comment by marco-m** [comment]
Ah, I think that the biggest showstopper is that now you build the DMG with build_mac_package.sh, which uses qmake. But it seems it could be easily made to use cmake instead than qmake. I'll give it a go.

**Comment by sieren** [comment]
Wow! That's awesome!!! Thanks a lot :)
I'll verify and test this locally as well before hitting the merge button.

**Comment by sieren** [comment]
Alright, did some quick investigating... to do an actual deployment we'd need to run a post-build command (`~/Qt/5.7/clang_64/bin/macdeployqt QSyncthingTray.app -dmg -verbose=2`) in the build directory. That'll copy over all the Qt Frameworks into the app. The behaviour on Windows would be similar (`windeployqt --compiler-runtime ...`) - I think this should be fairly straight forward to add. Then we can ditch QtCreator entirely.

**Comment by marco-m** [comment]
Ok. I put this branch on hold, I want to do small commits. I will post a PR to add macdeployqt to cmake, then we will clean up cmakelists, then this branch, then cmake package the correct way.

**Comment by sieren** [comment]
Havent forgotten about this, will take care of it ASAP

**Comment by marco-m** [comment]
:-)

**Comment by sieren** [comment]
Great!
Verified under OSX and Win. Works nicely!
Thanks for putting the work and effort into this 👍

**Comment by marco-m** [comment]
Yeah!

**Pull request merged**
