### PR TITLE
I14/fix process grepping whitespace

### PR DESCRIPTION
**Pull request by sieren**
Addressed Issue: https://github.com/sieren/QSyncthingTray/issues/14

### CODE REVIEW

**Comment by ech1965** [comment]
Much better when using quotes around program name !

Thanks for the quick support !
EC

**Comment by scalp42** [comment]
@sieren any chance for a release?

**Comment by sieren** [comment]
@scalp42 I'll try and get one out today or tomorrow

**Comment by sieren** [comment]
@scalp42 I just had a look, this should be in 0.4.3

**Comment by sieren** [comment]
Nevermind, I was wrong. It's not ;) 0.4.4 it is then

**Comment by ech1965** [comment]
Thanks for the 0.4.4 release !!

It looks like there is a glitch in the dmg filename ( still named 0.4.3 …)
Hav ea good night

De :  Matt Sieren <notifications@github.com>
Répondre à :  sieren/QSyncthingTray <reply@reply.github.com>
Date :  dimanche 20 mars 2016 17:58
À :  sieren/QSyncthingTray <QSyncthingTray@noreply.github.com>
Cc :  Etienne Charlier <etienne@charlier.info>
Objet :  Re: [QSyncthingTray] I14/fix process grepping whitespace (#92)


@scalp42 I just had a look, this should be in 0.4.3

**Comment by sieren** [comment]
Thanks... renamed it!

**Pull request merged**
