### PR TITLE
scripts: use better names

### PR DESCRIPTION
**Pull request by marco-m**
Very simple commit.

Actually, are the scripts in this directory used at all? We could even just get rid of them (or integrate what is possible in cmake)

### CODE REVIEW

**Comment by sieren** [comment]
Hey,

you're right. They're mostly legacy and pre-Cmake. We can get rid of them (except for the mac package one).
I'd leave this PR open if you want to add a commit on top.

Thanks! 👍

**Comment by marco-m** [comment]
I always like `rm` things :-)

**Comment by sieren** [comment]
The content of `clean.sh` is still used during packaging.
But I wouldnt mind just moving those lines into https://github.com/sieren/QSyncthingTray/pull/194/commits/6bdf3d8350a290a7c2c224e0728ff10a1d8e4433

**Comment by marco-m** [comment]
Resurrected clean.sh

**Pull request merged**
